

drop table EVPOPULATION.RAWDATA.EV_DATA_RW; 

delete from EVPOPULATION.RAWDATA.JSON_META_CONFIG_DM_RW;

delete from EVPOPULATION.RAWDATA.JSON_DATA_PARSED_FT_RW;

drop table EVPOPULATION.EV_CORE.JSON_META_CONFIG_DM;

drop table EVPOPULATION.EV_CORE.JSON_DATA_PARSED_FT;

drop table EVPOPULATION.EV_RFND.EV_MK_MODEL_AGG;

drop table EVPOPULATION.EV_RFND.EV_TOP_SALES_BY_MAKE_AGG;


select * from EVPOPULATION.RAWDATA.EV_DATA_RW;

select * from EVPOPULATION.RAWDATA.JSON_META_CONFIG_DM_RW;

select * from EVPOPULATION.RAWDATA.JSON_DATA_PARSED_FT_RW;

select * from EVPOPULATION.EV_CORE.JSON_DATA_PARSED_FT;

select * from EVPOPULATION.EV_RFND.EV_MK_MODEL_AGG;

EXECUTE TASK EVPOPULATION.RAWDATA.json_ingest_rt;
